# Generated by Django 2.2.3 on 2019-07-18 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_text', models.CharField(default=None, max_length=200)),
                ('user_text', models.CharField(default=None, max_length=200)),
                ('content', models.TextField()),
                ('scrape_time', models.CharField(max_length=50)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('url', models.CharField(default=None, max_length=200)),
            ],
        ),
    ]
