# Generated by Django 2.2.3 on 2019-07-15 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wikidata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='scrape_time',
            field=models.CharField(max_length=50),
        ),
    ]
