# Generated by Django 2.2.3 on 2019-11-03 13:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wikidata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='json_url',
            field=models.FileField(default=django.utils.timezone.now, storage='media', upload_to=''),
            preserve_default=False,
        ),
    ]
