# Generated by Django 2.2.3 on 2019-11-04 05:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wikidata', '0002_content_json_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='content',
        ),
        migrations.RemoveField(
            model_name='content',
            name='json_url',
        ),
        migrations.AddField(
            model_name='content',
            name='json_file',
            field=models.FileField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
    ]
