# Generated by Django 2.2.3 on 2019-07-15 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wikidata', '0002_auto_20190715_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='url',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
